### ISSUE TITLE
Summary tables broken on mobile

### ISSUE THREAD

**Issue by tombye** [alphagov/digitalmarketplace-frontend-toolkit#257]
Summary tables where the minimum width the `<tbody>` can fit in is more than the visual space given to it currently break out, pushing some of the content off-screen.

You can see this when viewing the example with multiple columns on mobile:

![summary_table_multiple_column_issue](https://cloud.githubusercontent.com/assets/87140/15141956/9c05efd0-169a-11e6-91ed-c7faae718910.png)

http://alphagov.github.io/digitalmarketplace-frontend-toolkit/summary-table.html

Note: this is not always to do with having more than 2 columns. It can also be seen with tables with 2 columns that have content which pushes the table with out:

![summary_table_css_issue](https://cloud.githubusercontent.com/assets/87140/15142023/05a9611a-169b-11e6-928b-6ce107ab00f5.png)

https://www.digitalmarketplace.service.gov.uk/digital-outcomes-and-specialists/opportunities/5

**Comment by pcraig3** [comment]
[Click here](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/) to read an article that might help.

**Comment by pcraig3** [comment]
```css
table.summary-item-body tbody td {
  /* default styles */
}
```
![screen shot 2016-05-16 at 15 38 01](https://cloud.githubusercontent.com/assets/2454380/15292962/a0c1da60-1b7d-11e6-8ebc-1e77cbc7abe7.png)

```css
table.summary-item-body tbody td {
  /* default styles */
  word-break: break-word;
}
```
![screen shot 2016-05-16 at 15 38 23](https://cloud.githubusercontent.com/assets/2454380/15292982/b3c58b70-1b7d-11e6-8522-c7831340898f.png)

```css
table.summary-item-body tbody td {
  /* default styles */
  word-break: break-all;
}
```
![screen shot 2016-05-16 at 15 38 41](https://cloud.githubusercontent.com/assets/2454380/15292993/bc8cb5da-1b7d-11e6-9898-408d48685b6b.png)

**Comment by pcraig3** [comment]
[Article mentioned above](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/) seems to prefer `overflow-wrap: break-word;` and `word-wrap: break-word;`, but neither of those rules seem to affect our tables (on Chrome, Safari, or FF).  But they must work in _some_ contexts, because they're the only rules being used in the [example given](http://codepen.io/team/css-tricks/pen/RWaNxr). 

Most browsers support [`word-break`](http://caniuse.com/#search=word-break) (except Opera Mini), but all browsers (at least partially) support [`word-wrap`](http://caniuse.com/#search=word-wrap).

Since I don't know how to test on Opera Mini, my suggestion would be something like:

```css
table.summary-item-body tbody td {
  /* ... */
  word-wrap: break-word;  /* fallback for word-break */ 
  word-break: break-word;
}
```
